#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

# begin with a number
# then a dash
# then strings and dashes
# finish with a string of characters
valid_branch_regex="^[0-9]+-[a-z-]+[a-z]+$"

message=$'Désolé ! Ton commit n\'est pas passé car ta branche est mal nommée :
1) Tu donnes un nouveau nom à ta branche, en le préfixant avec le numéro xx de l\'issue correspondante :
$ git branch -m xx-titre-de-ton-issue
2) Tu refais ton commit : cette-fois ci il va passer.
3) Tu supprimes la branche distante, qui a l\'ancien nom, et tu push ta branche locale, qui a le nouveau nom :
$ git push origin :ancien-nom nouveau-nom
4) Ta branche locale est toujours basée sur l\'ancienne branche distante, que tu viens de supprimer. Il faut donc la lier à la nouvelle branche distante :
$ git push origin -u nouveau-nom
Merci !

PS : si ta branche était déjà liée à une merge-request, elle a été fermée à l\'étape 3, quand tu as supprimé l\'ancienne branche distante. Il te faut en rouvrir une depuis la nouvelle branche.'

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
